# Generated by Django 5.1.15 on 2026-10-05 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('intro', models.TextField(blank=True, help_text='Describes product selection considerations. No performance guarantees or installation-service claims unless confirmed separately.')),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft (in review)'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_code', models.CharField(help_text='Internal mapping code, e.g. A, B, C (matches the catalogue mapping doc).', max_length=4, unique=True)),
                ('intro', models.TextField(blank=True, help_text='Original introductory copy shown at the top of the category page.')),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft (in review)'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('sku', models.CharField(blank=True, help_text='Internal SKU, if assigned.', max_length=60)),
                ('brand', models.CharField(blank=True, help_text='Verified brand/manufacturer only. Leave blank if unverified.', max_length=120)),
                ('synonyms', models.TextField(blank=True, help_text="Comma-separated search synonyms, e.g. 'fibre glass, fiberglass, glass wool'.")),
                ('short_summary', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True, help_text="Original descriptive copy. Do not copy another division's wording.")),
                ('sales_unit', models.CharField(blank=True, help_text="e.g. 'per sheet', 'per roll', 'per box'.", max_length=60)),
                ('minimum_order_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('moq_unit', models.CharField(blank=True, max_length=60)),
                ('availability_status', models.CharField(choices=[('in_stock', 'In stock'), ('on_order', 'Available on order'), ('unknown', 'Unknown / on enquiry')], default='unknown', max_length=10)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('status', models.CharField(choices=[('draft', 'Draft (in review)'), ('published', 'Published')], default='draft', max_length=10)),
                ('review_notes', models.TextField(blank=True, help_text='Unresolved identity notes, source references, or facts pending verification. Internal only — never rendered publicly.')),
                ('source_url', models.URLField(blank=True, help_text='Reference/source for verified facts.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('additional_categories', models.ManyToManyField(blank=True, related_name='secondary_products', to='catalog.category')),
                ('applications', models.ManyToManyField(blank=True, related_name='products', to='catalog.application')),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_products', to='catalog.category')),
                ('related_products', models.ManyToManyField(blank=True, to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('doc_type', models.CharField(choices=[('datasheet', 'Datasheet'), ('msds', 'Safety data sheet'), ('other', 'Other')], default='datasheet', max_length=12)),
                ('file', models.FileField(upload_to='documents/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=160)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Shown to the buyer, e.g. '50mm, 24kg/m³' or '1/4 in (6.35mm)'.", max_length=160)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('thickness', models.CharField(blank=True, max_length=60)),
                ('dimensions', models.CharField(blank=True, max_length=120)),
                ('density', models.CharField(blank=True, max_length=60)),
                ('diameter', models.CharField(blank=True, max_length=60)),
                ('box_capacity', models.CharField(blank=True, max_length=60)),
                ('pack_size', models.CharField(blank=True, max_length=60)),
                ('sales_unit_override', models.CharField(blank=True, max_length=60)),
                ('availability_status', models.CharField(choices=[('in_stock', 'In stock'), ('on_order', 'Available on order'), ('unknown', 'Unknown / on enquiry')], default='unknown', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
