# Generated by Django 5.2.17 on 2026-10-06 02:31

import catalog.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_path', models.CharField(help_text='e.g. /products/old-slug', max_length=300, unique=True)),
                ('new_path', models.CharField(help_text='e.g. /products/new-slug', max_length=300)),
            ],
            options={
                'ordering': ['old_path'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'name'], 'permissions': [('publish_product', 'Can publish or unpublish products')]},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='application',
            name='considerations',
            field=models.TextField(blank=True, help_text='One selection consideration per line, shown as a checklist.'),
        ),
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), catalog.uploads.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='application',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='summary',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='quote_checklist',
            field=models.TextField(blank=True, help_text='One item per line: details buyers should include in a quotation request for this category.'),
        ),
        migrations.AddField(
            model_name='product',
            name='selection_notes',
            field=models.TextField(blank=True, help_text='One item per line: what a buyer should confirm or tell us when requesting this product. Shown on the product page.'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Untick to keep an internal reference document off the website.'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to hide from buyers.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), catalog.uploads.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text="Original descriptive copy. Blank lines separate paragraphs. Do not copy another division's wording."),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank unless confirmed.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_unit',
            field=models.CharField(blank=True, help_text="Confirmed unit only, e.g. 'sheet', 'roll', 'box'.", max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Public URL: /products/<slug>. Changing it on a published product creates a permanent redirect from the old URL automatically.', max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, help_text='Internal reference/source for verified facts. Not shown publicly.'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), catalog.uploads.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(help_text='Describe what the photograph actually shows.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), catalog.uploads.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='label',
            field=models.CharField(help_text="Shown to the buyer, e.g. '50 mm' or '1/4 in (6.35 mm)'.", max_length=160),
        ),
    ]
