# Generated by Django 5.2.17 on 2026-10-06 03:05

import catalog.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_redirect_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (in review)'), ('published', 'Published'), ('archived', 'Hidden (outside current focus)')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (in review)'), ('published', 'Published'), ('archived', 'Hidden (outside current focus)')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (in review)'), ('published', 'Published'), ('archived', 'Hidden (outside current focus)')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Public URL: /services/<slug>.', max_length=140, unique=True)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True, help_text='Blank lines separate paragraphs.')),
                ('includes', models.TextField(blank=True, help_text='One item per line: what the service covers.')),
                ('request_checklist', models.TextField(blank=True, help_text='One item per line: what the customer should tell us when requesting it.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), catalog.uploads.validate_image_upload])),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft (in review)'), ('published', 'Published'), ('archived', 'Hidden (outside current focus)')], default='draft', max_length=10)),
                ('review_notes', models.TextField(blank=True, help_text='Internal only — never shown publicly.')),
                ('related_products', models.ManyToManyField(blank=True, related_name='services', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
