# Generated by Django 5.2.17 on 2026-10-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_application_status_alter_category_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='faqs',
            field=models.TextField(blank=True, help_text="Frequently asked questions shown on the page (and marked up for search engines). Write each as 'Q: question' on one line and 'A: answer' on the next; separate with a blank line."),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confirmed selling price (leave blank for quote-only).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, help_text="e.g. 'per brick', 'per 25 kg bag'.", max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='price_valid_until',
            field=models.DateField(blank=True, help_text='Date after which the price must be reconfirmed.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='faqs',
            field=models.TextField(blank=True, help_text="Frequently asked questions shown on the page (and marked up for search engines). Write each as 'Q: question' on one line and 'A: answer' on the next; separate with a blank line."),
        ),
    ]
