# Generated by Django 5.2.17 on 2026-10-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_faqs_product_price_product_price_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(help_text="As the customer agreed to be named, e.g. 'Jane W.'", max_length=120)),
                ('customer_role', models.CharField(blank=True, help_text="Optional, e.g. 'Owner, Example Pizzeria' (with permission).", max_length=160)),
                ('location', models.CharField(blank=True, help_text="Optional town, e.g. 'Nairobi'.", max_length=120)),
                ('quote', models.TextField(help_text="The customer's own words. Do not edit their meaning.")),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 / 5'), (2, '2 / 5'), (3, '3 / 5'), (4, '4 / 5'), (5, '5 / 5')], help_text='Only if the customer gave a rating.', null=True)),
                ('topic', models.CharField(choices=[('pizza', 'Pizza ovens'), ('cyclones', 'Roof cyclones'), ('general', 'General')], default='general', max_length=10)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('consent_confirmed', models.BooleanField(default=False, help_text='Tick only when the customer has agreed to this being published on the website.')),
                ('is_placeholder', models.BooleanField(default=False, editable=False, help_text='Example text created by the system; can never be published.')),
                ('status', models.CharField(choices=[('draft', 'Draft (in review)'), ('published', 'Published'), ('archived', 'Hidden (outside current focus)')], default='draft', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='catalog.service')),
            ],
            options={
                'ordering': ['order', '-received_on', '-created_at'],
            },
        ),
    ]
