# Generated by Django 5.1.15 on 2026-10-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='KariVex Industrial Materials', max_length=120)),
                ('division_descriptor', models.CharField(default='Industrial Materials Division', max_length=120)),
                ('parent_company_name', models.CharField(default='KariVex Solutions Ltd', max_length=120)),
                ('relationship_wording', models.CharField(default='A division of KariVex Solutions Ltd', max_length=160)),
                ('tagline', models.CharField(default='Strength Behind Every Project', max_length=120)),
                ('chemical_division_name', models.CharField(default='KariVex Chemical Division', max_length=120)),
                ('chemical_division_url', models.URLField(default='https://karivexsolutionsltd.com/')),
                ('primary_phone', models.CharField(default='+254 742 355548', max_length=30)),
                ('secondary_phone', models.CharField(blank=True, default='+254 710 851911', max_length=30)),
                ('whatsapp_number_intl', models.CharField(default='254710851911', help_text='Digits only, international format, no leading +. Used to build wa.me links.', max_length=20)),
                ('email', models.EmailField(default='info@karivexsolutionsltd.com', max_length=254)),
                ('address_line', models.CharField(default='Enterprise Road, Industrial Area, Nairobi, Nairobi County 00400, Kenya', max_length=200)),
                ('hours_text', models.CharField(default='Monday–Friday 08:00–17:00; Saturday 08:00–13:00', max_length=160)),
                ('regions_served', models.CharField(default='Kenya, Uganda, Tanzania, Rwanda', max_length=200)),
                ('contact_source_url', models.URLField(default='https://karivexsolutionsltd.com/contact', help_text='Where these contact details were last verified.')),
                ('contact_verified_on', models.DateField(blank=True, null=True)),
                ('production_origin', models.URLField(default='https://materials.karivexsolutionsltd.com')),
                ('ga_measurement_id', models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX. Leave blank to disable analytics.', max_length=32)),
                ('homepage_headline', models.CharField(default='Industrial Materials for Construction, Insulation & High-Temperature Applications', max_length=160)),
                ('homepage_intro', models.TextField(blank=True)),
                ('logo_header_override', models.ImageField(blank=True, help_text='Optional replacement for the bundled header logo derivative.', null=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
