# Generated by Django 5.2.17 on 2026-10-06 02:31

import catalog.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_enabled',
            field=models.BooleanField(default=True, help_text='Untick to hide the website enquiry forms (call/email/WhatsApp stay).'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='chemical_division_name',
            field=models.CharField(default='KariVex Solutions Ltd — Chemical Division', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_header_override',
            field=models.ImageField(blank=True, help_text='Optional replacement for the bundled header logo derivative.', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), catalog.uploads.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone',
            field=models.CharField(default='+254 710 851911', help_text='Main sales line, as displayed.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_phone',
            field=models.CharField(blank=True, default='+254 742 355548', help_text='Alternative sales line.', max_length=30),
        ),
    ]
