# Generated by Django 5.2.17 on 2026-10-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_sitesettings_contact_form_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_headline',
            field=models.CharField(default='Pizza Oven Materials, Building & Repair', max_length=160),
        ),
    ]
