# Generated by Django 5.2.17 on 2026-10-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_alter_sitesettings_homepage_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone',
            field=models.CharField(default='+254 742 355548', help_text='Main sales line, as displayed.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_phone',
            field=models.CharField(blank=True, default='+254 710 851911', help_text='Alternative sales line.', max_length=30),
        ),
    ]
