# Generated by Django 5.2.17 on 2026-10-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_swap_primary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_review_url',
            field=models.URLField(blank=True, help_text="Your Google Business Profile 'Ask for reviews' link. Shown as 'Review us on Google'."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_headline',
            field=models.CharField(default='Pizza Ovens & Roof Cyclones, Supplied, Built & Repaired', max_length=160),
        ),
    ]
