# Generated by Django 5.1.15 on 2026-10-05 15:32

import django.db.models.deletion
import enquiries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=enquiries.models.generate_reference_number, editable=False, max_length=32, unique=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Client-generated key preventing accidental double submission.', max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('delivery_location', models.CharField(blank=True, max_length=200)),
                ('project_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('quoted', 'Quoted'), ('closed', 'Closed')], default='new', max_length=12)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=180)),
                ('variant_label_snapshot', models.CharField(blank=True, max_length=160)),
                ('category_snapshot', models.CharField(blank=True, max_length=120)),
                ('product_url_snapshot', models.CharField(blank=True, max_length=300)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=60)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enquiries.enquiry')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
