# Generated by Django 5.2.17 on 2026-10-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Staff-only notes.'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='kind',
            field=models.CharField(choices=[('quote', 'Quotation request'), ('contact', 'General enquiry')], default='quote', max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='notification_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryitem',
            name='sku_snapshot',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='enquiryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
