# Generated by Django 5.2.17 on 2026-10-06 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_application_status_alter_category_status_and_more'),
        ('enquiries', '0002_enquiry_internal_notes_enquiry_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='service_name_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='kind',
            field=models.CharField(choices=[('quote', 'Quotation request'), ('contact', 'General enquiry'), ('service', 'Service request')], default='quote', max_length=10),
        ),
    ]
